version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - whitespace

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/DanielBlei/go-to-rag

issues:
  max-same-issues: 0
  exclude-dirs:
    - internal/gen
